unicef/etools-action-points

src/elements/core-elements/app-config/etools-app-config.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.js, src/elements/core-elements/app-shell-element/app-shell.html, src/elements/core-elements/app-shell-element/app-shell.js, src/elements/styles-elements/app-theme.html
Let me know if this PR should be opened against master instead of develop.
=> Adds conditional rendering of header colors/staging message

src/elements/core-elements/app-main-header/app-main-header/app-main-header.html, src/elements/data-elements/user-data.html
=> Fixes how countries_available is nested inside user object

src/elements/core-elements/app-shell-element/app-shell.html
=> fixes modal overaly

src/elements/core-elements/app-main-header/app-main-header/app-main-header.js
=> Changes logout link to /logout

src/elements/core-elements/app-config/etools-app-config.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.js, src/elements/core-elements/app-shell-element/app-shell.html, src/elements/core-elements/app-shell-element/app-shell.js
=> Adds env notification for remaining envs to header

index.html, src/elements/common-elements/support-btn.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html
=> [PROD] Support tool update

src/elements/common-elements/search-and-filter-element/search-and-filter.html, src/elements/common-elements/search-and-filter-element/search-and-filter.js
=> Allows for search/filter with as few as 1 character

bower.json, src/elements/core-elements/app-shell-element/app-shell.html
=> Adds etools-piwik-analytics

src/elements/app-mixins/user-controller.html, src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/user-data.html
=> Fixes endpoints and updates export endpoint

src/elements/pages/action-points-page-components/action-points-list/action-points-list.scss
=> Gives cells overflow:hidden property

src/elements/core-elements/app-config/etools-app-config.html, src/elements/pages/action-points-page-components/action-points-list/action-points-list.js
=> Updates users endpoint to 'api/v3/users'

bower.json
=> Updates etools-profile-dialog to 3.1.1

src_ts/elements/core-elements/app-main-header/app-main-header.ts
=> Fix header bg color

package.json, src_ts/elements/core-elements/app-main-header/app-main-header.ts
=> Upgrades etools-app-selector to v3.1.0

package.json
=> Updates app selector

src_ts/elements/common-elements/pages-header-element.ts, src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch18782] Remove Export Button on single Action Point detail page
=> [ch18782] Remove Export Button on single Action Point detail page

src_ts/elements/common-elements/status-element.ts
[ch19993]Action Point: When Action point is finalized, the button turns blue
=> [ch19993]Action Point: When Action point is finalized, the button turns blue

src_ts/elements/common-elements/multi-notifications/multi-notification-list.ts
[ch21070]Action Point: Toast messages not showing
=> [ch21070]Action Point: Toast messages not showing

express.js, package.json, polymer.json
=> [ch21370] Remove es5 build

src_ts/elements/core-elements/page-footer.ts
[ch24946] Action Points has an horizontal scroll
=> [ch24946] Action Points has an horizontal scroll

src_ts/elements/core-elements/app-main-header/countries-dropdown.ts
[ch25135] Current country display issue
=> [ch25135] Current country display issue

src_ts/elements/common-elements/search-and-filter.ts
[ch25116] Action Points: Make filter dropdown wider such that options won't span 2 lines
=> [ch25116] Action Points: Make filter dropdown wider such that options won't span 2 lines & add Clear All filters btn

src_ts/app-shell.ts, src_ts/elements/core-elements/etools-app-config.ts, src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch25133] Search is hidden under header
=> Fix dropdown

src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch25138] Intermittent: Continuous Loading screen + console error using filters and using pagination menu
=> [ch25138] Intermittent: Continuous Loading screen + console error using filters and using pagination menu

.eslintrc.json, src_ts/elements/core-elements/app-main-header/countries-dropdown.ts, src_ts/elements/data-elements/user-data.ts
=> [ch25192]Redirect to landing page when user not logged in or session expired

src_ts/elements/common-elements/search-and-filter.ts
[ch25198] Add `None` option to dropdown filters
=> [ch25198] Add `None` option to dropdown filters

src_ts/elements/pages/action-points-page-components/action-points-list.ts, src_ts/elements/styles-elements/status-styles.ts
=> [ch25194]Status component style issue on smaller screen width

src_ts/elements/common-elements/search-and-filter.ts, src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch25184] Remove redundant BE calls from the page list
=> [ch25184] Remove redundant BE calls from the page list

.gitignore, src_ts/elements/pages/action-points-page-components/action-points-list.ts
=> [ch25206]'Show Completed' toggle appears on 2 lines style issue

src_ts/elements/common-elements/search-and-filter.ts, src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch25616] Fix "Show Completed" toggle
=> [ch25616] Fix "Show Completed" toggle

src_ts/elements/app-mixins/localization-mixin.ts, src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch25694] Action Points: Column "Related App" is showing blank for all on the Results list
=> [ch25694] Action Points: Column "Related App" is showing blank for all on the Results list

src_ts/elements/core-elements/app-sidebar-menu.ts, src_ts/elements/styles-elements/nav-menu-styles.ts
=> [ch25895]Show arrow to the rigth when left side menu is minimized

src_ts/elements/pages/action-points-page-components/action-points-list.ts
[ch25909] [AP] Make the list responsive
=> [ch25909] [AP] Make the list responsive

package-lock.json, package.json
=> [ch25846]update app-selector

src_ts/elements/app-mixins/localization-mixin.ts, src_ts/elements/pages/action-points-page-components/action-point-details.ts
[ch26282] Information not consistent between list-view and detail-view (partner, pd output)
=> [ch26282] Information not consistent between list-view and detail-view (partner, pd output)

src_ts/elements/app-mixins/endpoints.ts
[ch25641] Action Points Interventions API takes a long time
=> [ch25641] Action Points Interventions API takes a long time

.circleci/config.yml, index.html, polymer.json, src_ts/app-shell.ts, version.json
[ch26249]Notify the user to refresh page when a new version of the app has been deployed
=> [ch26249]Notify the user to refresh page when a new version of the app has been deployed

src_ts/elements/common-elements/search-and-filter.ts, src_ts/elements/pages/action-points-page-components/action-point-details.ts
=> [ch26568]Format date display

.eslintrc.json, src_ts/app-shell.ts, src_ts/elements/app-mixins/app-menu-mixin.ts, src_ts/elements/app-mixins/endpoint-mixin.ts, src_ts/elements/app-mixins/error-handler-mixin.ts, src_ts/elements/app-mixins/input-attrs-mixin.ts, src_ts/elements/app-mixins/user-controller.ts, src_ts/elements/common-elements/multi-notifications/multi-notification-list.ts, src_ts/elements/common-elements/pages-header-element.ts, src_ts/elements/common-elements/search-and-filter.ts, src_ts/elements/common-elements/status-element.ts, src_ts/elements/data-elements/action-points-data.ts, src_ts/elements/data-elements/static-data.ts, src_ts/elements/data-elements/user-data.ts, src_ts/elements/pages/action-points-page-components/action-point-comments.ts, src_ts/elements/pages/action-points-page-components/action-point-details.ts, src_ts/elements/pages/action-points-page-components/action-points-history.ts, src_ts/elements/pages/action-points-page-components/action-points-item.ts, src_ts/elements/pages/action-points-page-components/action-points-list.ts, src_ts/elements/pages/action-points-page-components/action-points-new.ts, src_ts/elements/pages/action-points-page-components/action-points-page-main.ts, src_ts/elements/pages/action-points-page-components/open-add-comments.ts, src_ts/elements/pages/action-points-page-components/open-view-history.ts
=> [ch26621]Manual ts/eslint fixes

src_ts/elements/common-elements/support-btn.ts
[ch26816] Update support link in header
=> [ch26816] Update support link in header

src_ts/elements/common-elements/etools-action-buttons.ts
=> [ch26565]Button style tweak

package-lock.json, src_ts/elements/pages/action-points/detail/action-point-details.ts
=> [ch27509]Expand the description field when there is a large amount of text

src_ts/elements/common-elements/search-and-filter.ts, src_ts/elements/pages/action-points/detail/open-add-comments.ts, src_ts/elements/styles/module-styles.ts, src_ts/elements/styles/tab-inputs-styles.ts
[ch27502] Style issues -Inconsistent coloring
=> [ch27502] Style issues -Inconsistent coloring

src_ts/elements/pages/action-points/detail/action-point-details.ts
[ch27541] FE validation not working for 'Due On' & Page remains in Loading state
=> [ch27541] FE validation not working for 'Due On' & Page remains in Loading state

src_ts/elements/pages/action-points/detail/action-point-details.ts
[ch27546] Action Point Details: PD/SSFA and CP Output weird loading behavior after save or complete of the Action Point
=> [ch27546] Action Point Details: PD/SSFA and CP Output weird loading behavior after save or complete

package-lock.json, package.json, src_ts/elements/app-shell-components/app-main-header/app-main-header.ts
[ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol
=> [ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol

package-lock.json, package.json
[ch27477] [etools-dropdown] When Request is In Progress do not show msg to Scroll down
=> [ch27477] [etools-dropdown] When Request is In Progress do not show msg to Scroll down

src_ts/app-shell.ts, src_ts/elements/app-shell-components/app-main-header/countries-dropdown.ts, src_ts/elements/data-elements/action-points-data.ts, src_ts/elements/pages/action-points/action-points-new.ts, src_ts/elements/pages/action-points/action-points-page-main.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts, src_ts/elements/pages/not-found-page-view.ts
=> [ch28227]Fix redirect to 404

src_ts/app-shell.ts, src_ts/elements/app-shell-components/app-main-header/countries-dropdown.ts, src_ts/elements/data-elements/action-points-data.ts, src_ts/elements/pages/action-points/action-points-new.ts, src_ts/elements/pages/action-points/action-points-page-main.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts, src_ts/elements/pages/not-found-page-view.ts
=> [ch28229]Fix perpetual loading spinners

src_ts/elements/pages/action-points/action-points-page-main.ts
=> [ch28227]Fix navigation

package-lock.json, package.json
[ch28625] Handle security issues on repos
=> [ch28625] Handle security issues on repos

src_ts/elements/app-shell-components/app-sidebar-menu.ts
[ch28826] eTools Community Channels: Information returns 404
=> [ch28826] eTools Community Channels: Information returns 404

package-lock.json, package.json, src_ts/elements/pages/action-points/action-points-list.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/open-add-comments.ts
[ch29052] Migration to Lit issues
=> [ch29052] Migration to Lit issues

src_ts/elements/pages/action-points/detail/action-point-comments.ts
=> [ch29054] UI issues

package-lock.json, package.json, src_ts/elements/app-shell-components/app-sidebar-menu.ts, src_ts/elements/common-elements/pages-header-element.ts, src_ts/elements/common-elements/support-btn.ts, src_ts/elements/styles/apd-icons.ts, src_ts/elements/styles/nav-menu-styles.ts
[ch17503] Update Matomo tracking
=> [ch17503] Update Matomo tracking

src_ts/elements/pages/action-points/action-points-list.ts
[ch29102] Never ending loading after doing a sort on list + hard reload
=> [ch29102] Never ending loading after doing a sort on list + hard reload

src_ts/elements/app-shell-components/app-sidebar-menu.ts
=> [ch29414]Update Implementation Intelligence link

src_ts/elements/app-shell-components/app-sidebar-menu.ts
=> [ch29414]Implem. Intell. link

src_ts/elements/pages/action-points/action-points-new.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts
=> [ch30806]Handle users no longer assigned to country

src_ts/elements/pages/action-points/detail/action-points-item.ts
[ch30825]  Duplicate requests on page refresh/direct access of Action Point
=> [ch30825]  Duplicate requests on page refresh/direct access of Action Point

src_ts/elements/app-shell-components/app-main-header/app-main-header.ts
[ch32541] implement logout with redirect Azure ADB2C with the same effect as the "social/unicef-logout" url has in PRP.
=> [ch32541] implement logout with redirect Azure ADB2C with the same effect as the "social/unicef-logout" url has in PRP.

src_ts/elements/data-elements/static-data.ts
=> [ch33541]Auto-change language to English

src_ts/elements/app-shell-components/app-main-header/app-main-header.ts, src_ts/elements/app-shell-components/app-main-header/organizations-dropdown.ts, src_ts/endpoints/endpoints.ts
[ch33667] Add organization dropdown
=> [ch33667] Add organization dropdown

src_ts/elements/app-shell-components/app-main-header/countries-dropdown.ts, src_ts/elements/app-shell-components/app-main-header/organizations-dropdown.ts
[ch33762] Navigation issue on country change
=> [ch33762] Navigation issue on country change

src_ts/app-shell.ts, src_ts/config/config.ts, src_ts/elements/app-shell-components/app-main-header/countries-dropdown.ts, src_ts/elements/data-elements/static-data.ts
=> [ch33668]Mitigate app being partially translated 2

package-lock.json, package.json
[ch33803] Add AMP to etools-app-selector
=> [ch33803] Add AMP to etools-app-selector

src_ts/elements/app-shell-components/app-main-header/app-main-header.ts
=> [ch33849]Fix hard refresh btn

src_ts/elements/data-elements/user-data.ts
[ch34604] Non UNICEF users to be redirected to menu page when access Action Points module
=> [ch34604] Non UNICEF users to be redirected to menu page when access Action Points module

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/elements/app-shell-components/app-main-header/app-main-header.ts, src_ts/elements/app-shell-components/app-main-header/header-dropdown-styles.ts, src_ts/elements/app-shell-components/page-footer.ts, src_ts/elements/app-shell-components/side-bar-item.ts, src_ts/elements/common-elements/pages-header-element.ts, src_ts/elements/mixins/date-mixin.ts, src_ts/elements/pages/action-points/action-points-list.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/action-points-history.ts, src_ts/elements/pages/action-points/detail/open-add-comments.ts, src_ts/elements/styles/tab-inputs-styles.ts
[ch36234] Action Points optimize for small screen, mobile friendly
=> [ch36234] Action Points optimize for small screen, mobile friendly

assets/css/app-theme.css, src_ts/elements/common-elements/etools-action-buttons.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts
9.The COMPLETE button background is blue when an `Action Point ' is opened from FAM or FM
=> [ch36212] Action Points Shoelace Migration Issues

src_ts/elements/common-elements/status-element.ts, src_ts/elements/mixins/permission-controller.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts, src_ts/elements/pages/action-points/detail/add-verifier-dialog.ts, src_ts/elements/pages/action-points/detail/verify-dialog.ts, src_ts/elements/styles/tab-inputs-styles.ts
[ch36043] Segregation of duties for addressing the financial findings both in FAM and AP modules.
=> [ch36043] Segregation of duties for addressing the financial findings both in FAM and AP modules.

src_ts/elements/pages/action-points/action-points-list.ts
10. Mobile improvement Action Points - For better consistency when the table is empty due to 0 return we should add a message No records found
=> [ch36212] Table No records found fix

src_ts/app-shell.ts, src_ts/elements/app-shell-components/app-main-header/app-main-header.ts, src_ts/elements/app-shell-components/app-main-header/countries-dropdown.ts, src_ts/elements/app-shell-components/app-main-header/header-dropdown-styles.ts, src_ts/elements/app-shell-components/app-main-header/organizations-dropdown.ts, src_ts/elements/app-shell-components/app-sidebar-menu.ts, src_ts/elements/app-shell-components/side-bar-item.ts, src_ts/elements/common-elements/support-btn.ts, src_ts/elements/mixins/app-menu-mixin.ts, src_ts/elements/pages/action-points/action-points-list.ts, src_ts/elements/styles/shared-styles.ts, src_ts/elements/styles/tab-inputs-styles.ts
=> Header, sidebar, list fixes

src_ts/elements/styles/page-layout-styles.ts, src_ts/elements/styles/status-styles.ts
=> Layout fixes

package-lock.json, package.json
=> Fix dropdown width issue

src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts, src_ts/elements/pages/action-points/detail/add-verifier-dialog.ts
Fix Pd loading, reviewers options
=> Fix Pd loading, reviewers options

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/elements/pages/action-points/action-points-list.ts, src_ts/elements/pages/action-points/action-points-page-main.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts, src_ts/redux/store.ts
=> [ch36579] PWA Helpers

src_ts/elements/data-elements/action-points-data.ts
=> [ch36680] error aborted

src_ts/elements/pages/action-points/detail/action-point-comments.ts, src_ts/elements/pages/action-points/detail/open-add-comments.ts, src_ts/elements/pages/action-points/detail/open-view-history.ts, src_ts/endpoints/endpoints.ts
[ch36044] Enable Action point Module to store the supporting Documentations required for closure.
=> [ch36044] Enable Action point Module to store the supporting Documentations required for closure.

src_ts/elements/common-elements/status-element.ts, src_ts/elements/mixins/error-handler-mixin.ts, src_ts/elements/mixins/permission-controller.ts, src_ts/elements/pages/action-points/detail/action-point-comments.ts, src_ts/elements/pages/action-points/detail/action-point-details.ts, src_ts/elements/pages/action-points/detail/action-points-item.ts, src_ts/elements/pages/action-points/detail/verify-dialog.ts
[ch38359] Action Points changes for BOA
=> [ch38359] Action Points changes for BOA

package-lock.json, package.json, src_ts/elements/pages/action-points/action-points-list.ts, src_ts/elements/pages/action-points/detail/action-point-comments.ts
[ch39554] Move `pagination-mixin` to `etools-unicef/etools-data-table`,  it is used only by this component, update apps
=> [ch39554] Move `pagination-mixin` to `etools-unicef/etools-data-table`,  it is used only by this component, update apps

src_ts/elements/pages/action-points/action-points-list.ts
[259691] Pagination issues and improvements
=> [259691] Pagination issues and improvements

src_ts/elements/pages/action-points/action-points-new.ts
=> [275973] Fix loading error
